haskell-ricochet
================
shak-mar, brotknust, Bez, sternenseemann, hackalive, Hanfi10
:toc:
:showtitle:

A wip Haskell library for http://ricochet.im[ricochet.im].

== Idea

We really like Ricochet but the application is a monolithic Qt-based one.

We are developing this library for those reasons:

* Different frontends – like ncurses
* Possibility to build bots
* Easier to extend the protocol using new channel types (adding these is meant to be easy using our library)

== Stability and Security

Don't use this project unless you are developing on it. It is probably neither stable nor secure and far from being finished.

== Building and Documentation

We tested everything using the following nix-workflow but you should also get it to work using stack or cabal.

[source,shell]
----
cabal2nix . > haskell-ricochet.nix
nix-shell -A env                       # for dependencies
cabal configure
cabal build
cabal haddock                          # documentation
cabal repl                             # for playing around
cabal test                             # tests (need tor running with control port open)
----

== Get in touch!

* …with the https://github.com/ricochet-im/ricochet#other[original ricochet-developers]
* …with us: `#ricochet` on Freenode
